version: 2.1 # 設定ファイルのバージョン
jobs:
  test: # job名: 好きな名前を付けれます
    docker: # Dockerを使って環境構築するための宣言
      - image: circleci/ruby:2.6.3-stretch-node # 使用するDockerのイメージ
    steps:
      - checkout # リポジトリのコードをDocker内に持っていく
      - run:
          name: echo # echoという名前で実行する
          command: echo "Hello, world!!"
workflows: # workflowのバージョンも指定できますが、なくても動きます！
  test_workflow: # workflowの名前
    jobs:
      - test # 実行するjobの順番